## Zigbee 프로토콜 패킷 분리

In [1]:
import pandas as pd

log_zgb = pd.read_csv('RSSI_20_1000.log', delimiter=',', names=["Time","Id","Type","Data", "Start delimiter", "Length", "Frame type",
                                                            "64-bit source address", "16-bit source address", "Receive options",
                                                            "RF data", "Checksum"])

In [2]:
log_zgb

,Time,Id,Type,Data,Start delimiter,Length,Frame type,64-bit source address,16-bit source address,Receive options,RF data,Checksum
0,02-05-2022 23:29:59.579,-,API,"Router,0013A20041C37EFF,ZIGBEE TH Reg,4061,COM...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,02-05-2022 23:09:06.857,0,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02-05-2022 23:09:07.356,1,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02-05-2022 23:09:07.854,2,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-05-2022 23:09:08.414,3,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
996,02-05-2022 23:17:34.308,995,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,02-05-2022 23:17:34.870,996,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,02-05-2022 23:17:35.369,997,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,02-05-2022 23:17:35.868,998,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,02-05-2022 23:17:36.367,999,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
log_zgb = log_zgb.drop(index = 0, axis = 0)

In [4]:
log_zgb

,Time,Id,Type,Data,Start delimiter,Length,Frame type,64-bit source address,16-bit source address,Receive options,RF data,Checksum
1,02-05-2022 23:09:06.857,0,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,02-05-2022 23:09:07.356,1,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02-05-2022 23:09:07.854,2,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,02-05-2022 23:09:08.414,3,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,02-05-2022 23:09:08.909,4,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
996,02-05-2022 23:17:34.308,995,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,02-05-2022 23:17:34.870,996,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,02-05-2022 23:17:35.369,997,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,02-05-2022 23:17:35.868,998,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,02-05-2022 23:17:36.367,999,RECV,7E0020900013A20041C5375A0000013132333435363738...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
log_zgb.set_index("Id", inplace=True) #id로 인덱스 재지정

In [6]:
log_zgb.Data #패킷 데이터 확인

Id
0      7E0020900013A20041C5375A0000013132333435363738...
1      7E0020900013A20041C5375A0000013132333435363738...
2      7E0020900013A20041C5375A0000013132333435363738...
3      7E0020900013A20041C5375A0000013132333435363738...
4      7E0020900013A20041C5375A0000013132333435363738...
                             ...
995    7E0020900013A20041C5375A0000013132333435363738...
996    7E0020900013A20041C5375A0000013132333435363738...
997    7E0020900013A20041C5375A0000013132333435363738...
998    7E0020900013A20041C5375A0000013132333435363738...
999    7E0020900013A20041C5375A0000013132333435363738...
Name: Data, Length: 1000, dtype: object

In [7]:
log_zgb["Start delimiter"] = log_zgb.Data.str[:2]
log_zgb["Length"] = log_zgb.Data.str[2:6]
log_zgb["Frame type"] = log_zgb.Data.str[6:8]
log_zgb["64-bit source address"] = log_zgb.Data.str[8:24]
log_zgb["16-bit source address"] = log_zgb.Data.str[24:28]
log_zgb["Receive options"] = log_zgb.Data.str[28:30]
log_zgb["RF data"] = log_zgb.Data.str[30:-2] #페이로드 사이즈에 따라 위치 재조정 필요. 이 경우 20byte
log_zgb["Checksum"] = log_zgb.Data.str[-2:] #각각의 사이즈에 맞게 스플릿

In [8]:
log_zgb = log_zgb.drop(columns = "Data") #헷갈리니까 삭제

In [9]:
log_zgb

,Time,Type,Start delimiter,Length,Frame type,64-bit source address,16-bit source address,Receive options,RF data,Checksum
Id,,,,,,,,,,
0,02-05-2022 23:09:06.857,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
1,02-05-2022 23:09:07.356,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
2,02-05-2022 23:09:07.854,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
3,02-05-2022 23:09:08.414,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
4,02-05-2022 23:09:08.909,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
...,...,...,...,...,...,...,...,...,...,...
995,02-05-2022 23:17:34.308,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
996,02-05-2022 23:17:34.870,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
997,02-05-2022 23:17:35.369,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
998,02-05-2022 23:17:35.868,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08
999,02-05-2022 23:17:36.367,RECV,7E,0020,90,0013A20041C5375A,0000,01,3132333435363738393031323334353637383930,08

## 802.15.4 패킷 분리

In [10]:
log_802 = pd.read_csv('api_console_session_2022-02-06.log', delimiter=',', names=["Time","Id","Type", "Data", "Start delimiter",
                                                                                  "Length", "Frame type", "16-bit source address",
                                                                                  "RSSI", "Options", "RF data", "Checksum"])

In [11]:
log_802 = log_802.drop(index = 0, axis = 0)

In [12]:
log_802.set_index("Id", inplace=True)

In [13]:
log_802["Start delimiter"] = log_802.Data.str[:2]
log_802["Length"] = log_802.Data.str[2:6]
log_802["Frame type"] = log_802.Data.str[6:8]
log_802["16-bit source address"] = log_802.Data.str[8:12]
log_802["RSSI"] = log_802.Data.str[12:14]
log_802["Options"] = log_802.Data.str[14:16]
log_802["RF data"] = log_802.Data.str[16:-2] #페이로드 사이즈에 따라 위치 재조정 필요
log_802["Checksum"] = log_802.Data.str[-2:]

In [14]:
log_802.Data

Id
0      7E00198100003300313233343536373839306162636465...
1      7E00198100003300313233343536373839306162636465...
2      7E00198100003300313233343536373839306162636465...
3      7E00198100003300313233343536373839306162636465...
4      7E00198100003300313233343536373839306162636465...
                             ...
991    7E00198100002D00313233343536373839306162636465...
992    7E00198100002E00313233343536373839306162636465...
993    7E00198100002E00313233343536373839306162636465...
994    7E00198100002D00313233343536373839306162636465...
995    7E00198100002E00313233343536373839306162636465...
Name: Data, Length: 996, dtype: object

In [15]:
log_802 = log_802.drop(columns = "Data")

In [16]:
log_802

,Time,Type,Start delimiter,Length,Frame type,16-bit source address,RSSI,Options,RF data,Checksum
Id,,,,,,,,,,
0,02-06-2022 20:52:35.816,RECV,7E,0019,81,0000,33,00,313233343536373839306162636465666768696A,47
1,02-06-2022 20:52:35.878,RECV,7E,0019,81,0000,33,00,313233343536373839306162636465666768696A,47
2,02-06-2022 20:52:36.002,RECV,7E,0019,81,0000,33,00,313233343536373839306162636465666768696A,47
3,02-06-2022 20:52:36.128,RECV,7E,0019,81,0000,33,00,313233343536373839306162636465666768696A,47
4,02-06-2022 20:52:36.189,RECV,7E,0019,81,0000,33,00,313233343536373839306162636465666768696A,47
...,...,...,...,...,...,...,...,...,...,...
991,02-06-2022 20:54:24.925,RECV,7E,0019,81,0000,2D,00,313233343536373839306162636465666768696A,4D
992,02-06-2022 20:54:24.987,RECV,7E,0019,81,0000,2E,00,313233343536373839306162636465666768696A,4C
993,02-06-2022 20:54:25.114,RECV,7E,0019,81,0000,2E,00,313233343536373839306162636465666768696A,4C
994,02-06-2022 20:54:25.240,RECV,7E,0019,81,0000,2D,00,313233343536373839306162636465666768696A,4D
995,02-06-2022 20:54:25.365,RECV,7E,0019,81,0000,2E,00,313233343536373839306162636465666768696A,4C