# 테스트 및 실험용 코드

In [1]:
import pandas as pd
import numpy as np

log_20_4_5 = pd.read_csv('./packet_log/20byte_distance_4.5m.log', delimiter=',', names=["Time","Id","Type", "Data", "Start delimiter",
                                                                                  "Length", "Frame type", "16-bit source address",
                                                                                  "RSSI", "Options", "RF data", "Checksum"])

In [2]:
log_20_4_5 = log_20_4_5.drop(index = 0, axis = 0)

In [3]:
log_20_4_5.set_index("Id", inplace=True)

log_20_4_5["Start delimiter"] = log_20_4_5.Data.str[:2]
log_20_4_5["Length"] = log_20_4_5.Data.str[2:6]
log_20_4_5["Frame type"] = log_20_4_5.Data.str[6:8]
log_20_4_5["16-bit source address"] = log_20_4_5.Data.str[8:12]
log_20_4_5["RSSI"] = log_20_4_5.Data.str[12:14]
log_20_4_5["Options"] = log_20_4_5.Data.str[14:16]
log_20_4_5["RF data"] = log_20_4_5.Data.str[16:-2]
log_20_4_5["Checksum"] = log_20_4_5.Data.str[-2:]

log_20_4_5

,Time,Type,Data,Start delimiter,Length,Frame type,16-bit source address,RSSI,Options,RF data,Checksum
Id,,,,,,,,,,,
0,02-12-2022 16:55:43.917,RECV,7E00198122224600202020202020202020202020202020...,7E,0019,81,2222,46,00,2020202020202020202020202020202020202030,64
1,02-12-2022 16:55:44.478,RECV,7E00198122224600202020202020202020202020202020...,7E,0019,81,2222,46,00,2020202020202020202020202020202020202031,63
2,02-12-2022 16:55:44.914,RECV,7E00198122224600202020202020202020202020202020...,7E,0019,81,2222,46,00,2020202020202020202020202020202020202032,62
3,02-12-2022 16:55:45.413,RECV,7E00198122224600202020202020202020202020202020...,7E,0019,81,2222,46,00,2020202020202020202020202020202020202033,61
4,02-12-2022 16:55:45.910,RECV,7E00198122224600202020202020202020202020202020...,7E,0019,81,2222,46,00,2020202020202020202020202020202020202034,60
...,...,...,...,...,...,...,...,...,...,...,...
989,02-12-2022 17:04:01.886,RECV,7E00198122224800202020202020202020202020202020...,7E,0019,81,2222,48,00,2020202020202020202020202020202020393935,2B
990,02-12-2022 17:04:02.389,RECV,7E00198122224800202020202020202020202020202020...,7E,0019,81,2222,48,00,2020202020202020202020202020202020393936,2A
991,02-12-2022 17:04:02.889,RECV,7E00198122224800202020202020202020202020202020...,7E,0019,81,2222,48,00,2020202020202020202020202020202020393937,29
992,02-12-2022 17:04:03.331,RECV,7E00198122224800202020202020202020202020202020...,7E,0019,81,2222,48,00,2020202020202020202020202020202020393938,28
993,02-12-2022 17:04:03.839,RECV,7E00198122224800202020202020202020202020202020...,7E,0019,81,2222,48,00,2020202020202020202020202020202020393939,27

In [4]:
log_20_4_5 = log_20_4_5.drop(columns = "Data") #원본 패킷 날림

In [5]:
def func(x):
    return int(x, 16)

log_20_4_5["Length"] = log_20_4_5["Length"].apply(func)

#  = int(log_20_4_5["Length"]) #길이를 10진수로 변환

In [6]:
log_20_4_5

,Time,Type,Start delimiter,Length,Frame type,16-bit source address,RSSI,Options,RF data,Checksum
Id,,,,,,,,,,
0,02-12-2022 16:55:43.917,RECV,7E,25,81,2222,46,00,2020202020202020202020202020202020202030,64
1,02-12-2022 16:55:44.478,RECV,7E,25,81,2222,46,00,2020202020202020202020202020202020202031,63
2,02-12-2022 16:55:44.914,RECV,7E,25,81,2222,46,00,2020202020202020202020202020202020202032,62
3,02-12-2022 16:55:45.413,RECV,7E,25,81,2222,46,00,2020202020202020202020202020202020202033,61
4,02-12-2022 16:55:45.910,RECV,7E,25,81,2222,46,00,2020202020202020202020202020202020202034,60
...,...,...,...,...,...,...,...,...,...,...
989,02-12-2022 17:04:01.886,RECV,7E,25,81,2222,48,00,2020202020202020202020202020202020393935,2B
990,02-12-2022 17:04:02.389,RECV,7E,25,81,2222,48,00,2020202020202020202020202020202020393936,2A
991,02-12-2022 17:04:02.889,RECV,7E,25,81,2222,48,00,2020202020202020202020202020202020393937,29
992,02-12-2022 17:04:03.331,RECV,7E,25,81,2222,48,00,2020202020202020202020202020202020393938,28
993,02-12-2022 17:04:03.839,RECV,7E,25,81,2222,48,00,2020202020202020202020202020202020393939,27

# 누락 및 비정상 패킷 비율

재전송해야하는 패킷을 구하기 위해서는 정상 패킷 수신 비율을 알아야 됨.

누락 패킷 = 전체 패킷 - 수신 패킷

이 경우, 전체 패킷은 1000개 이므로 수신 패킷의 정상 유무와 상관없이 1000에서 수신 패킷을 빼면 됨

shape[0]은 행 개수, shape[1]은 열 개수이므로 shape[0]을 이용해 쉽게 구할 수 있음

In [7]:
whole_packet = 1000

missed_packet = whole_packet - log_20_4_5.shape[0]

missed_packet

6

누락 및 비정상 패킷 수신 비율 = (누락 패킷 수 + 비정상 패킷 수) / 전체 패킷 수

RF data(=payload)의 값이 변하면 Length의 길이가 바뀌므로 비정상 패킷 판단 가능

In [8]:
abnormal_packet_rate = (missed_packet + log_20_4_5[log_20_4_5["Length"] != 25].shape[0]) / whole_packet

abnormal_packet_rate

0.008

전체 데이터 1,000,000 바이트를 보낸다고 가정했을 때,

20바이트씩 끊어서 보낸 경우 50,000번의 전송을 하고 (`1,000,000 / 20 = 50,000`) (전체 데이터 / 바이트 수)

0.008의 확률로 재전송을 해야하므로 재전송 횟수는 400회 (`(1,000,000 / 20) * 0.008 = 400`) ( (전체 데이터 / 바이트 수) * 이상 패킷 비율)

따라서 총 전송 횟수는 50,400회 (`(1,000,000 / 20) + (1,000,000 / 20) * 0.008`) (전체 데이터 / 바이트 수) + ((전체 데이터 / 바이트 수) * 이상패킷 비율)

총 전송 횟수 = (1,000,000 / 분할 바이트 수) + ((1,000,000 / 분할 바이트 수 * 누락 및 비정상 패킷 비율))

**이후의 모든 데이터는 1,000,000바이트로 가정함**

# 변수 자동 생성 및 로그 파일 자동 읽기

In [9]:
packet_distance_1 = ['0m', '9m', '18m'] # 정수만
packet_distance_2 = ['4.5m', '13.5m', '22.5m'] # 실수만

packet_distance = [*sum(zip(packet_distance_1, packet_distance_2),())] # 두개를 교차로 합쳐서 하나로 만들고
packet_distance.append('27m') #27은 append로 추가

packet_distance_name = ['0m', '4_5m', '9m', '13_5m', '18m', '22_5m', '27m']
# 문자열 리스트 하나로 만드는게 빠르긴 할 것 같다.
# 그대로 하면 뒤쪽에서 오류나기 때문에 리스트명 생성을 위해 언더바로 대체 리스트

packet_byte = list(range(20, 110, 10)) #20-110byte까지

range에서는 정수형으로밖에 사용할 수 없어서 numpy를 활용

In [10]:
packet_byte

[20, 30, 40, 50, 60, 70, 80, 90, 100]

In [11]:
packet_distance

['0m', '4.5m', '9m', '13.5m', '18m', '22.5m', '27m']

In [12]:
packet_distance_name

['0m', '4_5m', '9m', '13_5m', '18m', '22_5m', '27m']

## 동적으로 데이터프레임 생성

In [13]:
for i in packet_byte:
    for j, k in zip(packet_distance, packet_distance_name):
        globals()['log_' + str(i) + 'byte_distance_' + str(k)] = pd.read_csv('./packet_log/' + str(i) + 'byte_distance_' + str(j) +'.log', 
                                                                                  delimiter=',', names=["Time","Id","Type", "Data",
                                                                                                        "Start delimiter", "Length",
                                                                                                        "Frame type", "16-bit source address",
                                                                                                        "RSSI", "Options", "RF data", "Checksum"])

## 2차원 배열에 데이터프레임 이름 저장

In [14]:
log_list = []

for i in packet_byte:
    line = []
    for j, k in zip(packet_distance, packet_distance_name):
        globals()['log_' + str(i) + 'byte_distance_' + str(k)] = pd.read_csv('./packet_log/' + str(i) + 'byte_distance_' + str(j) +'.log', 
                                                                                  delimiter=',', names=["Time","Id","Type", "Data",
                                                                                                        "Start delimiter", "Length",
                                                                                                        "Frame type", "16-bit source address",
                                                                                                        "RSSI", "Options", "RF data", "Checksum"])
        line.append(['log_' + str(i) + 'byte_distance_' + str(k)])
    log_list.append(line)

In [15]:
log_list

[[['log_20byte_distance_0m'],
  ['log_20byte_distance_4_5m'],
  ['log_20byte_distance_9m'],
  ['log_20byte_distance_13_5m'],
  ['log_20byte_distance_18m'],
  ['log_20byte_distance_22_5m'],
  ['log_20byte_distance_27m']],
 [['log_30byte_distance_0m'],
  ['log_30byte_distance_4_5m'],
  ['log_30byte_distance_9m'],
  ['log_30byte_distance_13_5m'],
  ['log_30byte_distance_18m'],
  ['log_30byte_distance_22_5m'],
  ['log_30byte_distance_27m']],
 [['log_40byte_distance_0m'],
  ['log_40byte_distance_4_5m'],
  ['log_40byte_distance_9m'],
  ['log_40byte_distance_13_5m'],
  ['log_40byte_distance_18m'],
  ['log_40byte_distance_22_5m'],
  ['log_40byte_distance_27m']],
 [['log_50byte_distance_0m'],
  ['log_50byte_distance_4_5m'],
  ['log_50byte_distance_9m'],
  ['log_50byte_distance_13_5m'],
  ['log_50byte_distance_18m'],
  ['log_50byte_distance_22_5m'],
  ['log_50byte_distance_27m']],
 [['log_60byte_distance_0m'],
  ['log_60byte_distance_4_5m'],
  ['log_60byte_distance_9m'],
  ['log_60byte_distance_13_5m'],
  ['log_60byte_distance_18m'],
  ['log_60byte_distance_22_5m'],
  ['log_60byte_distance_27m']],
 [['log_70byte_distance_0m'],
  ['log_70byte_distance_4_5m'],
  ['log_70byte_distance_9m'],
  ['log_70byte_distance_13_5m'],
  ['log_70byte_distance_18m'],
  ['log_70byte_distance_22_5m'],
  ['log_70byte_distance_27m']],
 [['log_80byte_distance_0m'],
  ['log_80byte_distance_4_5m'],
  ['log_80byte_distance_9m'],
  ['log_80byte_distance_13_5m'],
  ['log_80byte_distance_18m'],
  ['log_80byte_distance_22_5m'],
  ['log_80byte_distance_27m']],
 [['log_90byte_distance_0m'],
  ['log_90byte_distance_4_5m'],
  ['log_90byte_distance_9m'],
  ['log_90byte_distance_13_5m'],
  ['log_90byte_distance_18m'],
  ['log_90byte_distance_22_5m'],
  ['log_90byte_distance_27m']],
 [['log_100byte_distance_0m'],
  ['log_100byte_distance_4_5m'],
  ['log_100byte_distance_9m'],
  ['log_100byte_distance_13_5m'],
  ['log_100byte_distance_18m'],
  ['log_100byte_distance_22_5m'],
  ['log_100byte_distance_27m']]]

## 반복문으로 데이터프레임 호출해보기

문자열 내부에 .이 들어가 있으면 오류가 생긴다.

예를 들자면, `log_20byte_distance_0m`는 괜찮은데 `log_20byte_distance_4.5m`는 오류가 생김

따라서 cm로 수정해야 하거나 언더바(_)로 대체해야 할듯

> 언더바로 대체됨

추가) 70byte의 27m와 같이 내부 데이터가 전혀 없는 경우 오류 발생

이러한 데이터를 처리하기 위한 방법이 필요함

> if not으로 비어있는지 여부 체크해서 해결

추가2) 한번에 처리하는게 좀 어려움

eval exec 함수로 처리 등등 다 해봤는데 잘 안됨.

> globals로 개별적으로 처리해서 동시에 처리 끝냄<br>
문자열이 포함된 변수 이름의 경우 이렇게 접근하는 편이 빠름

In [16]:
import sys
mod = sys.modules[__name__]

# eval('log_' + str(i) + 'byte_distance_' + str(j))

for i in packet_byte:
    for j in packet_distance_name:
        if not globals()['log_' + str(i) + 'byte_distance_' + str(j)].empty: #비어있는 데이터가 아니면 적절히 처리
            globals()['log_' + str(i) + 'byte_distance_' + str(j)] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].drop(index = 0, axis = 0)
            globals()['log_' + str(i) + 'byte_distance_' + str(j)].set_index("Id", inplace=True)
            
            #패킷 헤더 규격에 맞게 분리
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Start delimiter"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[:2]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Length"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[2:6]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Frame type"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[6:8]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["16-bit source address"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[8:12]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["RSSI"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[12:14]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Options"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[14:16]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["RF data"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[16:-2]
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Checksum"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].Data.str[-2:]
            
            #필요없는 기존 데이터 처리
            globals()['log_' + str(i) + 'byte_distance_' + str(j)] = globals()['log_' + str(i) + 'byte_distance_' + str(j)].drop(columns = "Data")
            
            #Length 16진수>>10진수 변환
            globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Length"] = globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Length"].apply(func)

# 자동 처리 끝

In [17]:
log_20byte_distance_18m

,Time,Type,Start delimiter,Length,Frame type,16-bit source address,RSSI,Options,RF data,Checksum
Id,,,,,,,,,,
0,02-12-2022 17:31:55.082,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020202030,5D
1,02-12-2022 17:31:55.581,RECV,7E,25,81,2222,4C,00,2020202020202020202020202020202020202031,5D
2,02-12-2022 17:31:56.081,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020202032,5B
3,02-12-2022 17:31:56.581,RECV,7E,25,81,2222,4A,00,2020202020202020202020202020202020202033,5D
4,02-12-2022 17:31:57.083,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020202034,59
...,...,...,...,...,...,...,...,...,...,...
943,02-12-2022 17:40:13.011,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020393935,26
944,02-12-2022 17:40:13.513,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020393936,25
945,02-12-2022 17:40:14.017,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020393937,24
946,02-12-2022 17:40:14.519,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020393938,23
947,02-12-2022 17:40:14.960,RECV,7E,25,81,2222,4D,00,2020202020202020202020202020202020393939,22

In [18]:
log_40byte_distance_4_5m

,Time,Type,Start delimiter,Length,Frame type,16-bit source address,RSSI,Options,RF data,Checksum
Id,,,,,,,,,,
0,02-12-2022 22:20:08.188,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,E2
1,02-12-2022 22:20:08.688,RECV,7E,45,81,2222,46,00,2020202020202020202020202020202020202020202020...,E3
2,02-12-2022 22:20:09.250,RECV,7E,45,81,2222,49,00,2020202020202020202020202020202020202020202020...,DF
3,02-12-2022 22:20:09.691,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,DF
4,02-12-2022 22:20:10.189,RECV,7E,45,81,2222,49,00,2020202020202020202020202020202020202020202020...,DD
...,...,...,...,...,...,...,...,...,...,...
978,02-12-2022 22:28:26.366,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,AB
979,02-12-2022 22:28:26.864,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,AA
980,02-12-2022 22:28:27.362,RECV,7E,45,81,2222,49,00,2020202020202020202020202020202020202020202020...,A8
981,02-12-2022 22:28:27.867,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,A8
982,02-12-2022 22:28:28.367,RECV,7E,45,81,2222,48,00,2020202020202020202020202020202020202020202020...,A7

In [19]:
log_70byte_distance_27m

Empty DataFrame
Columns: [Time, Id, Type, Data, Start delimiter, Length, Frame type, 16-bit source address, RSSI, Options, RF data, Checksum]
Index: []

# 패킷 전송 횟수 계산 테이블 생성

재전송 패킷의 누락/비정상 확률은 어떻게 처리하지? << 교수님께 물어보기

In [20]:
packet_table = pd.DataFrame({'0m':['0','0', '0', '0', '0', '0', '0', '0', '0']})
packet_table['4.5m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']
packet_table['9m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']
packet_table['13.5m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']
packet_table['18m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']
packet_table['22.5m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']
packet_table['27m'] = ['0','0', '0', '0', '0', '0', '0', '0', '0']

packet_table.index = ['20bytes', '30bytes', '40bytes', '50bytes', '60bytes', '70bytes', '80bytes', '90bytes', '100bytes']

In [21]:
packet_table

         0m 4.5m 9m 13.5m 18m 22.5m 27m
20bytes   0    0  0     0   0     0   0
30bytes   0    0  0     0   0     0   0
40bytes   0    0  0     0   0     0   0
50bytes   0    0  0     0   0     0   0
60bytes   0    0  0     0   0     0   0
70bytes   0    0  0     0   0     0   0
80bytes   0    0  0     0   0     0   0
90bytes   0    0  0     0   0     0   0
100bytes  0    0  0     0   0     0   0

총 전송 횟수 = (1,000,000 / 분할 바이트 수) + ((1,000,000 / 분할 바이트 수 * 누락 및 비정상 패킷 비율))

In [22]:
packet_byte_list = ['20bytes', '30bytes', '40bytes', '50bytes', '60bytes', '70bytes', '80bytes', '90bytes', '100bytes']

In [23]:
packet_byte

[20, 30, 40, 50, 60, 70, 80, 90, 100]

In [24]:
packet_byte_list

['20bytes',
 '30bytes',
 '40bytes',
 '50bytes',
 '60bytes',
 '70bytes',
 '80bytes',
 '90bytes',
 '100bytes']

In [25]:
packet_distance

['0m', '4.5m', '9m', '13.5m', '18m', '22.5m', '27m']

In [26]:
packet_distance_name

['0m', '4_5m', '9m', '13_5m', '18m', '22_5m', '27m']

전체 데이터 1,000,000 바이트를 보낸다고 가정했을 때,

20바이트씩 끊어서 보낸 경우 50,000번의 전송을 하고 (`1,000,000 / 20 = 50,000`) (전체 데이터 / 바이트 수)

0.008의 확률로 재전송을 해야하므로 재전송 횟수는 400회 (`(1,000,000 / 20) * 0.008 = 400`) ( (전체 데이터 / 바이트 수) * 이상 패킷 비율)

따라서 총 전송 횟수는 50,400회 (`(1,000,000 / 20) + (1,000,000 / 20) * 0.008`) (전체 데이터 / 바이트 수) + ((전체 데이터 / 바이트 수) * 이상패킷 비율)

총 전송 횟수 = (1,000,000 / 분할 바이트 수) + ((1,000,000 / 분할 바이트 수 * 누락 및 비정상 패킷 비율))

**이후의 모든 데이터는 1,000,000바이트로 가정함**

In [27]:
import math

for i, k in zip(packet_byte, packet_byte_list):
    for j, m in zip(packet_distance_name, packet_distance): #거리 목록, 분할 바이트 수
        if not globals()['log_' + str(i) + 'byte_distance_' + str(j)].empty: 
#             print(f"{i}, {j}") #디버깅용
            send_data = 1000000
            whole_packet = 1000
            
            missed_packet = whole_packet - globals()['log_' + str(i) + 'byte_distance_' + str(j)].shape[0] #누락 패킷 탐지
#             print(missed_packet) #누락 패킷 개수
    
            abnormal_packet_rate = (missed_packet + len(globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Length"][globals()['log_' + str(i) + 'byte_distance_' + str(j)]["Length"] != int(i) + 5])) / whole_packet
            #비정상 패킷 비율 = (누락 패킷 + 길이가 다른 수신 패킷) / 전체 패킷
                        
            total_send = math.ceil((send_data / int(i)) + (send_data / int(i)) * abnormal_packet_rate)
#             print(total_send)
            #재전송을 포함한 전체 전송율 (소수로 나눠지는 경우 올림처리)
            
            packet_table[m][k] = total_send
#             테이블에 집어넣음

In [28]:
packet_table

             0m   4.5m     9m  13.5m    18m  22.5m    27m
20bytes   50000  50400  50250  52550  52600  53900  99450
30bytes   33334  33767  33800  34534  33767  34100  65567
40bytes   25000  25475  25325  26950  26550  26175  39950
50bytes   20000  20440  20320  21420  20380  20680  39580
60bytes   16667  16834  16800  17300  17017  17584  33234
70bytes   14286  14429  14486  14815  14886  14643      0
80bytes   12500  12763  12725  13050  12775  12850  24575
90bytes   11112  11434  11345  11723  11312  11356      0
100bytes  10000  10040  10120  10350  10190  10300  10300

# 확인용?

In [29]:
print(math.ceil(send_data / 30))

missed_packet = whole_packet - log_30byte_distance_18m.shape[0]
print(missed_packet)

abnormal_packet_rate = (missed_packet + len(log_30byte_distance_18m["Length"][log_30byte_distance_18m["Length"] != 35])) / whole_packet
print(abnormal_packet_rate)

total_send = math.ceil((send_data / 30) + (send_data / 30) * abnormal_packet_rate)
print(total_send)

33334
13
0.013
33767

# 한계?

**실험 데이터가 상당히 들쭉날쭉함**

27m거리의 경우, 극단적으로 전송이 잘 되거나 되지 않거나 하는 등의 문제가 있음

당초 계획대로라면 40m였는데 27m에서도 이러한 현상이 두드러져서 어쩔 수 없이 범위를 줄이고 간격을 조금 늘림

**재전송 패킷의 재전송 확률 등을 고려해야 하는가**

당연한 얘기지만 재전송하는 경우에도 패킷 손실이 일어날 수 있음

이러한 상황에 대해 고려하지 않았음

**동일한 길이로 변형된 패킷은 알 수가 없음**

재전송을 포함하더라도 payload의 length만 고려했기 때문에 **헤더 전체를 포함해서 테이블을 생성해야 하는가에 대한 의논이 필요**

필요하다면 아래 수식대로 테이블을 덮어쓰면 되기 때문에 큰 어려움 없음

> 재전송, 헤더를 모두 포함한 전체 패킷 전송 바이트 수 = ( length + 5 ) * 전송 횟수

# 연습장...

In [30]:
temp = pd.DataFrame([[0,0,0,0],[1,1,1,1],[2,2,2,2]])

In [31]:
temp

   0  1  2  3
0  0  0  0  0
1  1  1  1  1
2  2  2  2  2

In [32]:
temp[0][2] = "a"

In [33]:
temp

   0  1  2  3
0  0  0  0  0
1  1  1  1  1
2  a  2  2  2